### ISSUE TITLE
Size of a share or folder

### ISSUE THREAD

**Issue by MK0151** [fastlta/sb-public#16]
Hello FastLTA team,

how to query the used size for a share or a folder in the volume?

With kind regards
MK0151

**Comment by jj-projects** [comment]
Hello MK0151,

size of shares and folders are not specifically available.
The system provides volumes or in case of an WORM archive additionally sub volumes.
The _size_ and the _used space_ are properties of those (sub)_volumes_.
Please look at https://github.com/fastlta/sb-public/blob/master/docs/public_api.md#list-volumes for details.

Sample of my test system:

> https://<ip-address>/sb-public-api/api/v1/volumes.json  results in 

>  {
>     "volumes": [
>         {
>             "name": "Repli_FSR",
>             "uuid": "f717fd1a-0e61-47de-b51b-4f2fa924a364",
>             "description": "",
>             "nas_engine": "nas",
>             "mode": "replication",
>             "size": 834449408,
>             "used": 3624960,
>             "status": "offline",
>             "volume_type": "snas_3p"
>         },
>         {
>             "name": "OT_1",
>             "uuid": "36507d62-f8fc-4062-873b-e9dfd0be18d2",
>             "description": "Opentext Test 1",
>             "nas_engine": "sub",
>             "mode": "plain",
>             "size": 0,
>             "used": 0,
>             "config": {
>                 "privDelMode": "compliance"
>             },
>             "status": "online",
>             "volume_type": "sub_volume",
>             "brick_archive_uuid": "bff5aab2-9435-11ea-82aa-72b349c3432e"
>         }
>     ]
> }
> 
> 

To test this you can use e.g. _Postman_ with a GET _call_ and _Basic Auth_

**Comment by MK0151** [comment]
We use the system without WORM. Is there also the possibility to create sub-volumes with the system without WORM? We have use cases where several customers share a Brick. In order to bill them reasonably, it would be helpful if we could track the individual consumptions.

**Comment by webrene** [comment]
Hi MK0151,
when using non-WORM devices, we are talking about Volumes instead of sub volumes. Volumes can not be partitioned any further, which means that we can only deliver fill states of the whole volume (identified by its ID). Since the Silent Bricks are modular it may be an alternative to use per-user Volumes though which means to assign Bricks+Volumes to users instead of Shares.
